# Required when using verl.utils.omega_conf_to_dataclass to instantiate dataclass configs
_target_: verl.workers.config.TeacherHFModelConfig

# specify the default per-component configs
defaults:

  # distillation config, inheriting from trainer/config/model/hf_model.yaml
  # Use absolute path + @_here_ to flatten fields at current level
  - /model/hf_model@_here_

  # load the default config, then apply the fields in the current yaml
  # self config override anything above
  - _self_

# Domain of the teacher; corresponds to the reward_fn_key for the data that the teacher will be used to acquire knowledge on.

# Domain(s) of the teacher; corresponds to the reward_fn_key(s) for data corresponding to the teacher.
# Does not need to be specified in single-teacher setups.
domain: null

# Huggingface model path; if null, the teacher is considered inactive
path: null

# Number of GPUs per node to use for this teacher model; if null, the teacher resource pool will be split evenly across all active teachers
num_gpus_per_node: null